name: deploy-auth

on:
    push:
        branches:
            - main
        paths:
            - 'packages/auth/**'

defaults:
    run:
        working-directory: packages/auth

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2         

            - name: Install dependencies
              run: npm install

            - name: Build container
              run: npm run build

            - name: get access to aws cli
              run : shinyinc/action-aws-cli@v1.2

            - name: run on awc cli
              run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth/latest
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


            - name: invallidate index.html
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/auth/latest/index.html"
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}             